services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot-etc:/var/www/certbot
    depends_on:
      - app-service
      - auth-service

  app-service:
    image: dobleuber/app-service
    restart: always
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP:-auth-service}
    expose:
      - "8000"
    depends_on:
      auth-service:
        condition: service_started

  auth-service:
    image: dobleuber/auth-service
    restart: always
    expose:
      - "8080"

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-etc:/var/www/certbot