services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf/nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-service
      - auth-service

  app-service:
    image: dobleuber/app-service
    build: ./app-service
    restart: always
    environment:
      AUTH_SERVICE_IP: auth-service
    expose:
      - "8000"
    depends_on:
      auth-service:
        condition: service_started

  auth-service:
    image: dobleuber/auth-service
    build: ./auth-service
    restart: always
    env_file:
      - ./.env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "mysql://root:${DATABASE_PASSWORD}@db:3306"
      DATABASE_NAME: bootcamp
      MAIL_AUTH_TOKEN: ${MAIL_AUTH_TOKEN}
    expose:
      - "8080"
    depends_on:
      - db
  db:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: bootcamp
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local