services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-etc:/var/www/certbot
    depends_on:
      - app-service
      - auth-service

  app-service:
    image: dobleuber/app-service
    restart: always
    environment:
      AUTH_SERVICE_IP: auth-service
    expose:
      - "8000"
    depends_on:
      auth-service:
        condition: service_started

  auth-service:
    image: dobleuber/auth-service
    restart: always
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: "mysql://root:${DATABASE_PASSWORD}@db:3306"
      DATABASE_NAME: bootcamp
    expose:
      - "8080"
    depends_on:
      - db

  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-etc:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email dobleuber@gmail.com -d dobleuber.lat --agree-tos
  
  db:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: bootcamp
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local